### ISSUE TITLE
which becoder can I use?

### ISSUE THREAD

**Issue by vicvinc** [whtsky/maga#4]
here is the error:

```

Traceback (most recent call last):
  File "example.py", line 1, in <module>
    from maga import Maga
  File "C:\Users\o\Desktop\simDHT-master\maga.py", line 10, in <module>
    from bencoder import bencode, bdecode
ImportError: cannot import name 'bencode'
```

thx

**Comment by whtsky** [comment]
https://github.com/whtsky/bencoder.pyx

**Comment by vicvinc** [comment]
thx again
